version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: sactis
      POSTGRES_PASSWORD: 54891329
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: